#
#List of the twelve payloads types
#with connected missions [id] and [names]
#and extended name
#

FIELDS = {
    "opt_sensor": {
        "missions_id": [
            14,
            378,
            385,
            259,
            82,
            265,
            346,
            303,
            311,
            270,
            347,
            258,
            382,
            55,
            31,
            137,
            8,
            387,
            77,
            383,
            386,
            170,
            261,
            51
        ],
        "missions": [
            "2001 Mars Odyssey",
            "ATHENA",
            "Chandra",
            "Cassini",
            "WISE (NEOWISE)",
            "Deep Impact (EPOXI)",
            "Euclid",
            "Gaia",
            "HERSCHEL",
            "Hubble Space Telescope",
            "JUICE",
            "Juno",
            "LOFT",
            "Mars 2020 Rover",
            "Mars Express",
            "Mars Global Surveyor",
            "New Horizons",
            "Nustar",
            "Rosetta",
            "STE-QUEST",
            "STEREO",
            "Venus Express",
            "Voyager 2",
            "Voyager 1"
        ],
        "name": "Optical Sensor",
        "kw": "visible light optical",
        "keywords": ["imaging", "lenses", "visible"]
    },
    "infrared": {
        "missions_id": [
            14,
            259,
            311,
            265,
            346,
            303,
            270,
            347,
            31,
            137,
            8,
            299,
            77,
            354,
            51,
            261
        ],
        "missions": [
            "2001 Mars Odyssey",
            "Cassini",
            "HERSCHEL",
            "Deep Impact (EPOXI)",
            "Euclid",
            "Gaia",
            "Hubble Space Telescope",
            "JUICE",
            "Mars Express",
            "Mars Global Surveyor",
            "New Horizons",
            "LISA",
            "Rosetta",
            "TRMM",
            "Voyager 1",
            "Voyager 2"
        ],
        "name": "Infrared sensor",
        "kw": "infrared spectrum",
    },
    "microwave": {
        "missions_id": [
            14,
            354,
            355,
            311,
            347,
            258,
            299,
            77,
            383
        ],
        "missions": [
            "2001 Mars Odyssey",
            "TRMM",
            "Gpm",
            "HERSCHEL",
            "JUICE",
            "Juno",
            "LISA",
            "Rosetta",
            "STE-QUEST"
        ],
        "name": "Microwave sensor",
        "kw": "microwaves",
    },
    "particles": {
        "missions_id": [
            14,
            52,
            259,
            311,
            347,
            382,
            31,
            137,
            74,
            77,
            292,
            384,
            261,
            269
        ],
        "missions": [
            "2001 Mars Odyssey",
            "Huygens",
            "Cassini",
            "HERSCHEL",
            "JUICE",
            "LOFT",
            "Mars Express",
            "Mars Global Surveyor",
            "MAVEN",
            "Rosetta",
            "Solar-Orbiter",
            "Van_Allen RBSP",
            "Voyager 2",
            "Voyager 1"
        ],
        "name": "Particles Detector",
        "kw": "particles",
        "keywords": ["particles", "neutron", "proton"]
    },
    "radio_sensor": {
        "missions_id": [
            14,
            354,
            303,
            355,
            311,
            347,
            55,
            31,
            137,
            34,
            8,
            387,
            77,
            383,
            386,
            251,
            170,
            41
        ],
        "missions": [
            "2001 Mars Odyssey",
            "TRMM",
            "Gaia",
            "Gpm",
            "HERSCHEL",
            "JUICE",
            "Mars 2020 Rover",
            "Mars Express",
            "Mars Global Surveyor",
            "MESSENGER",
            "New Horizons",
            "Nustar",
            "Rosetta",
            "STE-QUEST",
            "STEREO",
            "GRAIL",
            "Venus Express",
            "Voyager 2"
        ],
        "name": "Radio Sensor",
        "kw": "radio waves",
    },
    "plasma": {
        "missions_id": [
            52,
            259,
            170,
            311,
            347,
            31,
            74,
            77,
            292,
            386,
            384,
            269,
            261
        ],
        "missions": [
            "Huygens",
            "Cassini",
            "Venus Express",
            "HERSCHEL",
            "JUICE",
            "Mars Express",
            "MAVEN",
            "Rosetta",
            "Solar-Orbiter",
            "STEREO",
            "Van_Allen RBSP",
            "Voyager 1",
            "Voyager 2"
        ],
        "name": "Plasma Analyzer",
        "kw": "plasma"
    },
    "x_rays": {
        "missions_id": [
            14,
            378,
            323,
            385,
            303,
            311,
            347,
            382,
            55,
            34,
            299,
            387,
            77,
            348
        ],
        "missions": [
            "2001 Mars Odyssey",
            "ATHENA",
            "XMM-Newton",
            "Chandra",
            "Gaia",
            "HERSCHEL",
            "JUICE",
            "LOFT",
            "Mars 2020 Rover",
            "MESSENGER",
            "LISA",
            "Nustar",
            "Rosetta",
            "Integral"
        ],
        "name": "X-rays sensor",
        "kw": "x-rays",
    },
    "ultraviolet": {
        "missions_id": [
            14,
            52,
            259,
            303,
            311,
            270,
            347,
            258,
            31,
            74,
            8,
            77,
            55,
            386,
            170,
            51,
            261
        ],
        "missions": [
            "2001 Mars Odyssey",
            "Huygens",
            "Cassini",
            "Gaia",
            "HERSCHEL",
            "Hubble Space Telescope",
            "JUICE",
            "Juno",
            "Mars Express",
            "MAVEN",
            "New Horizons",
            "Rosetta",
            "Mars 2020 Rover",
            "STEREO",
            "Venus Express",
            "Voyager 1",
            "Voyager 2"
        ],
        "name": "Ultraviolet sensor",
        "kw": "ultraviolet",
    },
    "mag": {
        "missions_id": [
            14,
            311,
            347,
            258,
            382,
            137,
            34,
            77,
            381,
            170,
            261,
            269
        ],
        "missions": [
            "2001 Mars Odyssey",
            "HERSCHEL",
            "JUICE",
            "Juno",
            "LOFT",
            "Mars Global Surveyor",
            "MESSENGER",
            "Rosetta",
            "THEMIS",
            "Venus Express",
            "Voyager 2",
            "Voyager 1"
        ],
        "name": "Magnetometer",
        "kw": "magnetic fields",
    },
    "gamma_rays": {
        "missions_id": [
            14,
            259,
            378,
            323,
            389,
            311,
            348,
            137,
            34,
            77
        ],
        "missions": [
            "2001 Mars Odyssey",
            "Cassini",
            "ATHENA",
            "XMM-Newton",
            "Nasa Fermi GLAST",
            "HERSCHEL",
            "Integral",
            "Mars Global Surveyor",
            "MESSENGER",
            "Rosetta"
        ],
        "name": "Gamma-rays sensor",
        "kw": "gamma-rays"
    },
    "grav": {
        "missions_id": [
            14,
            311,
            34,
            299,
            77
        ],
        "missions": [
            "2001 Mars Odyssey",
            "HERSCHEL",
            "MESSENGER",
            "LISA",
            "Rosetta"
        ],
        "name": "Gravitational wave detector",
        "kw": "gravitational wave",
    }
}